#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
service nginx restart
