#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
sed -i 'location /redirect_me {\n\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n'
service nginx restart
