#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/*
sudo touch /var/www/html/404.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > sudo /var/www/html/404.html
sudo chmod 644 /var/www/html/*
sudo sed -i '48i \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

sudo sed -i '52i \\tlocation = /404.html {\n\t\troot /var/www/html;\n\t}\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

sudo service nginx restart
