#!/usr/bin/env bash
# This script is displaying 1 to 20
n=101
i=1
while [ $i -ne $n ]
do
    if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i%3)) == 0 ]
    then
	echo "Fizz"
    elif [ $((i % 5)) == 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi
    let "i++"
done
