#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using while

file="/etc/passwd"
while IFS=: read -r f1 _ f3 _ _ f6 _
do

    printf '%s:%s:%s\n' "$f1" "$f3" "$f6"
done <"$file"
