#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and the 9th is Hi
n=11
i=1
while [ $i -ne $n ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    let "i++"
done
