#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using for
LIST="$(ls .)"

for i in $LIST
do
    len=${#i}
    for (( j=1; j<len; j++ ))
    do
	if [ "${i:$j:1}" == "-" ]
	then
	    break
	fi
    done
    if [ "$j" = "$len" ]
    then
	echo "$i"
    else
	let "j++"
	echo "${i:j}"
    fi
done
