#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and the 9th is Hi
n="./holbertonschool"

if [ -e "$n" ]
then
    echo "holbertonschool file exists"
    if [ -s "$n" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$n" ]
    then
echo "holbertonschool is a regular file"
    fi
else
echo "holbertonschool file does not exist"
fi
