#!/usr/bin/env bash
# Run Nginx as Nginx
sudo pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i '3i user nginx;' /etc/nginx/nginx.conf
chmod -R 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
